config/routes.rb
Rails.application.routes.draw do
  devise_for :users, class_name: "Users::Models::User"

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "cards#index"
  resources :cards, only: [:show]
  resources :card_collections do
    post "add_card", to: "card_collections#add_card", as: "add_card"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern
end

app/controllers/card_collections_controller.rb
class CardCollectionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @card_collections = current_user.card_collections.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    card_collection = ::CardManagement::Models::CardCollection.find(params[:id])
    grouped_ids = card_collection.card_ids.tally

    @grouped_cards = grouped_ids.map do |card_id, count|
      {
        card: ::Mtg::Models::Card.includes(:card_identifier).find(card_id),
        count:
      }
    end
  end

  def create
    permitted_params = params.permit(:name)
    card_collection = ::CardManagement::Models::CardCollection.new(
      name: permitted_params[:name],
      user_id: current_user.id
    )

    if card_collection.save
      redirect_to card_collections_path, notice: "Collection created successfully."
    else
      flash[:error] = card_collection.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def add_card
    permitted_params = add_card_params
    card_collection = ::CardManagement::Models::CardCollection.find(permitted_params[:card_collection_id])
    card_id = permitted_params[:card_id]
    card_count = permitted_params[:card_count].to_i
    card_collection.card_ids += [card_id] * card_count

    if card_collection.save
      redirect_to card_collection_path(card_collection), notice: "Card added successfully."
    else
      flash[:error] = card_collection.errors.full_messages.to_sentence
    end
  end

  private

  def add_card_params
    params.permit(:card_collection_id, :card_id, :card_count)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  include ViewsHelper

  def index
    @permitted_params = index_params.to_h
    @filters = ::Mtg::Models::Card::SIMPLE_FILTERS
    @cards = @permitted_params.present? ? fetch_filtered_cards(@permitted_params) : []
  end

  def show
    @permitted_params = show_params.to_h
    @card = ::Mtg::Models::Card.find(params[:id])
  end

  private

  def index_params
    params.permit(:name, :page, colors: [], types: [], rarities: [])
  end

  def show_params
    params.permit(:id, :name, :page, colors: [], types: [], rarities: [])
  end

  def fetch_filtered_cards(params)
    filtered_card_ids = fetch_filtered_card_ids(params)

    ::Mtg::Models::Card.includes(:card_identifier)
      .where(id: filtered_card_ids)
      .select("DISTINCT ON (name) *")
      .order(:name)
      .page(params[:page])
      .per(30)
  end

  def fetch_filtered_card_ids(params)
    ::Mtg::Services::Cards::SimpleFilter.call(params: filter_params(params))
  end

  def filter_params(params)
    {
      name: [params[:name]],
      colors: params[:colors],
      types: params[:types],
      rarity: params[:rarities]
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/views_helper.rb
module ViewsHelper
  def colors_filter_options
    colors = ::Mtg::Config.colors

    colors.map do |color|
      { label: color, value: color == "Blue" ? "U" : color[0] }
    end
  end

  def types_filter_options
    types = ::Mtg::Config.card_types

    types.map do |type|
      { label: type, value: type }
    end
  end

  def rarities_filter_options
    rarities = ::Mtg::Config.rarities

    rarities.map do |rarity|
      { label: rarity, value: rarity }
    end
  end
end

app/views/card_collections/_add_card_form.html.erb
<div class="flex flex-col space-y-4 mt-6">
  <div class="flex items-center space-x-4 w-full">
    <label for="card_collection_id" class="text-gray-300 w-1/3">Select collection:</label>
    <select name="card_collection_id" id="card_collection_id" class="border border-gray-700 bg-gray-900 text-gray-200 rounded-lg p-2 w-2/3" required>
      <option value="">Choose a collection</option>
      <% current_user.card_collections.each do |collection| %>
        <option value="<%= collection.id %>"><%= collection.name %></option>
      <% end %>
    </select>
  </div>

  <div id="card-form-container" class="mt-4"></div>

  <script>
    document.getElementById("card_collection_id").addEventListener("change", function() {
      const formContainer = document.getElementById("card-form-container");
      formContainer.innerHTML = "";

      if (this.value) {
        const cardCollectionId = this.value;

        formContainer.innerHTML = `
          <form action="/card_collections/${cardCollectionId}/add_card" method="post" class="flex items-center space-x-4 w-full">
            <input type="hidden" name="card_id" value="<%= @card.id %>">
            <label class="text-gray-300 w-1/3" for="card_count">Number of cards:</label>
            <input type="number" name="card_count" value="1" min="1" class="border border-gray-700 bg-gray-900 text-gray-200 rounded-lg p-2 w-2/3" required>
            <button type="submit" class="bg-blue-600 text-white font-semibold py-2 px-4 rounded-lg hover:bg-blue-500">Add card</button>
          </form>
        `;
      }
    });
  </script>
</div>

app/views/card_collections/index.html.erb
<%= link_to "Create a new collection", new_card_collection_path, class: "mt-4 inline-block bg-blue-600 text-white font-semibold py-2 px-4 rounded-lg hover:bg-blue-700" %>

<% if @card_collections.present? %>
  <div class="my-8">
    <div class="grid grid-cols-3 gap-6">
      <% @card_collections.each do |collection| %>
        <div class="flex flex-col items-center">
          <%= link_to image_tag("card_collection.png", title: collection.name, alt: collection.name, class: "w-full h-auto rounded"), card_collection_path(collection) %>
          <p class="text-white font-bold mt-2"><%= collection.name %></p>
          <p class="text-gray-400">Number of cards: <%= collection.card_ids.size %></p>
        </div>
      <% end %>
    </div>
  </div>

  <%= paginate @collection = @card_collections %>
  
<% else  %>
  <p class="text-gray-300 mt-8 text-xl">You have no collections.</p>
<% end %>

app/views/card_collections/new.html.erb
<div class="max-w-md mx-auto mt-8">
  <%= form_with(url: card_collections_path, local: true) do |form| %>
    <div class="mb-6">
      <%= form.label :name, "Collection Name:", class: "text-lg font-medium text-gray-300" %>
      <%= form.text_field :name, class: "border border-gray-700 bg-gray-900 text-gray-200 rounded-lg p-2 w-full", required: true %>
    </div>

    <% if flash[:error] %>
      <div class="mb-4 text-red-500">
        <%= flash[:error] %>
      </div>
    <% end %>

    <%= form.submit "Create Collection", class: "bg-blue-600 text-white font-semibold py-2 px-4 rounded-lg hover:bg-blue-700" %>
  <% end %>
</div>

app/views/card_collections/show.html.erb
<% if @grouped_cards.present? %>
  <div class="my-8">
    <div class="grid grid-cols-3 gap-6">
      <% @grouped_cards.each do |group| %>
        <div class="flex flex-col items-center">
          <%= image_tag(group[:card].image_url, title: group[:card].name, alt: group[:card].name, class: "w-full h-auto rounded") %>
          <p class="text-white mt-2"><%= group[:card].name %></p>
          <p class="text-gray-400">Number of cards: <%= group[:count] %></p>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <p class="text-gray-300 text-xl">This collection does not contain any cards.</p>
<% end %>

app/views/cards/_cards_list.html.erb
<% if @cards.present? %>
  <%= paginate @collection = @cards %>

  <div class="mt-8">
    <p class="text-gray-300">
      <%= "#{@cards.total_count} #{"card".pluralize(@cards.total_count)} found that match your criteria" %>
    </p>
  </div>
  <div class="my-8">
    <div class="grid grid-cols-3 gap-6">
      <% @cards.each do |card| %>
        <%= link_to image_tag(card.image_url, title: card.name, alt: card.name, class: "w-full h-auto rounded"), card_path(card, @permitted_params) %>
      <% end %>
    </div>
  </div>

  <%= paginate @collection = @cards %>

<% elsif @permitted_params.present? %>
  <p class="text-gray-300 text-xl">No cards found... 😞</p>
<% end %>

app/views/cards/_filter_field.html.erb
<div class="mt-4 space-y-2">
  <details
    class="filter-details overflow-hidden rounded border border-gray-300 rounded-lg dark:border-gray-600 [&_summary::-webkit-details-marker]:hidden"
  >
    <summary
      class="flex cursor-pointer items-center justify-between gap-2 bg-white p-4 text-gray-900 transition dark:bg-gray-900 dark:text-white"
    >
      <span class="text-sm font-medium"><%= title.capitalize %></span>

      <span class="transition group-open:-rotate-180">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="1.5"
          stroke="currentColor"
          class="size-4"
        >
          <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
        </svg>
      </span>
    </summary>

    <div class="border-t border-gray-200 bg-white dark:border-gray-700 dark:bg-gray-900">
      <ul class="space-y-1 border-t border-gray-200 p-4 dark:border-gray-700">
        <% options.each do |option| %>
          <li>
            <label for="filter_in_<%= title %>_<%= option[:label] %>" class="inline-flex items-center cursor-pointer gap-2">
              <input
                type="checkbox"
                id="filter_in_<%= title %>_<%= option[:label] %>"
                name="<%= title %>[]"
                value="<%= option[:value] %>"
                <%= "checked" if params[title]&.include?(option[:value]) %>
                class="size-5 rounded cursor-pointer border-gray-300 dark:border-gray-600 dark:bg-gray-900 dark:focus:ring-offset-gray-900"
              />
              <span class="text-sm font-medium text-gray-700 dark:text-gray-200">
                <%= option[:label] %>
              </span>
            </label>
          </li>
        <% end %>
      </ul>
    </div>
  </details>
</div>

<script>
  document.addEventListener("click", function(event) {
    document.querySelectorAll(".filter-details").forEach((details) => {
      if (!details.contains(event.target)) {
        details.removeAttribute("open");
      }
    });
  });
</script>

app/views/cards/_filters.html.erb
<div class="grid grid-cols-3 gap-4">
  <% filters.each do |filter| %>
    <%= render "cards/filter_field", title: filter, options: send("#{filter}_filter_options") %>
  <% end %>
</div>

app/views/cards/_index_header.html.erb
<header>
  <div class="flex justify-center">
    <%= image_tag "mtg_logo_2.png", title: "mtg_logo_2", alt: "mtg_logo_2", class: "inline-block w-32 h-auto" %>
  </div>  

  <h1 class="text-4xl font-bold text-center mb-6 text-gray-200">Magic The Gathering Card Search</h1>
</header>

app/views/cards/_search_form.html.erb
<%= form_with(url: root_path, local: true, method: :get, class: "mb-8") do |form| %>
  <div class="flex items-center space-x-4">
    <%= form.label "", "Search:", class: "text-lg font-medium text-gray-300" do %>
      <%= image_tag "mtg_logo.png", title: "mtg_logo", alt: "mtg_logo", class: "inline-block w-48 h-auto" %>
    <% end %>
    <%= form.text_field :name, value: params[:name], placeholder: "Search for Magic cards...", class: "border border-gray-700 bg-gray-900 text-gray-200 rounded-lg p-2 w-full" %>
    <%= form.submit "Search", class: "bg-gray-700 text-white font-semibold py-2 px-4 rounded-lg hover:bg-gray-600" %>
    <button type="button" onclick="clearFilters()" class="bg-red-700 text-white font-semibold py-2 px-4 rounded-lg hover:bg-red-600">
      Clear
    </button>
  </div>
  
  <%= render "cards/filters", filters: @filters %>
<% end %>

<script>
  function clearFilters() {
    const url = new URL(window.location.href);
    url.search = "";
    window.location.href = url.toString();
  }
</script>

app/views/cards/index.html.erb
<div class="max-w-6xl mx-auto p-8 pt-6">
  <%= render "cards/index_header" %>
  <%= render "cards/search_form" %>
  <%= render "cards/cards_list" %>
</div>

app/views/cards/show.html.erb
<div class="max-w-4xl mx-auto mt-8 p-8">
  <h1 class="text-4xl font-bold text-center mb-6 text-gray-200"><%= @card.name %></h1>

  <div class="flex flex-col items-center">
    <img src="<%= @card.image_url %>" title="<%= @card.name %>" alt="<%= @card.name %>" class="w-1/2 h-auto rounded mb-4" />
    
    <div class="text-gray-300 text-lg">
      <p><strong>Set:</strong> <%= @card.set_code %></p>
      <p><strong>Type:</strong> <%= @card.type %></p>
      <p><strong>Rarity:</strong> <%= @card.rarity %></p>
      <p><strong>Text:</strong> <%= @card.text %></p>
    </div>

    <% if user_signed_in? && current_user.card_collections.any? %>
      <%= render "card_collections/add_card_form" %>
    <% end %>


    <div class="mt-8">
      <%= link_to "← Back to search", root_path(@permitted_params), class: "bg-gray-600 text-white font-semibold py-2 px-4 rounded-lg hover:bg-gray-500" %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-gray-800 text-gray-300 py-4 mt-8 rounded-t-xl">
  <div class="max-w-6xl mx-auto flex justify-between items-center px-4">
    <p class="text-lg">© 2024 Magic The Gathering Card Manager</p>
    <p class="text-lg">Created by Kacper Łepecki</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-gray-800 shadow-md rounded-b-xl">
  <%= image_tag "header.png", title: "header", alt: "header", class: "w-full h-auto" %>

  <nav class="max-w-6xl mx-auto flex justify-between items-center p-4">
    <div class="flex space-x-4">
      <%= link_to "Home", root_path, class: "#{controller_name == "cards" ? "underline" : "text-white"} hover:text-blue-400 font-semibold" %>
      <% if user_signed_in? %>
        <%= link_to "My Collections", card_collections_path, class: "#{controller_name == "card_collections" ? "underline" : "text-white"} hover:text-blue-400 font-semibold" %>
      <% end %>
    </div>
    <div class="flex space-x-4">
      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, class: "text-white hover:text-red-400 font-semibold" %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, 
            class: "#{controller_name == "sessions" ? "underline" : "bg-blue-600"} text-white py-2 px-4 rounded-lg hover:bg-blue-700" %>
        <%= link_to "Sign Up", new_user_registration_path, 
            class: "#{controller_name == "registrations" ? "underline" : "bg-gray-500"} text-white py-2 px-4 rounded-lg hover:bg-gray-700" %>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/_layout.html.erb
<div class="flex flex-col min-h-screen">
  <%= render "layouts/header" %>

  <main class="flex-1 px-5">
    <%= yield %>
  </main>

  <%= render "layouts/footer" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Mtg Card Manager" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-900 text-gray-200">
    <div class="max-w-6xl mx-auto">
      <%= render "layouts/layout" %>
    </div>
  </body>
</html>